### ISSUE TITLE
是否可增加文章中单条数据的渲染

### ISSUE THREAD

**Issue by lmm214** [lizheming/doumark-action#1]
比如某篇文章中以hugo的短代码模式插入豆瓣链接，自动查询csv对应的数据并渲染成html

**Comment by lizheming** [comment]
这种感觉是不是还是提供个接口会更方便一点？

**Comment by lmm214** [comment]
像牧风一页api接口是最方便的，但这样数据集中在一起，还要维护吧？

**Comment by lizheming** [comment]
之前在 Railway 已经部署过一个独立服务，我之后找下接口加一下吧

**Comment by lizheming** [comment]
https://doumark.up.railway.app/movie/35144311 
https://doumark.up.railway.app/book/35481512
https://doumark.up.railway.app/music/35788348

已添加接口支持，我这边自己会做一次缓存，第一次请求完豆瓣之后就无关了，服务可用性应该没啥问题。可以试一下哈~
