### ISSUE TITLE
同步数据到notion 失败

### ISSUE THREAD

**Issue by ilikui** [lizheming/doumark-action#13]
提示API token is invalid

`APIResponseError: API token is invalid.
    at buildRequestError (/snapshot/drone-doumark/node_modules/@notionhq/client/build/src/errors.js:162:16)
    at Client.request (/snapshot/drone-doumark/node_modules/@notionhq/client/build/src/Client.js:304:54)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async NotionStore.get (/snapshot/drone-doumark/src/store/notion.js)
    at async exec (/snapshot/drone-doumark/src/plugin.js) {
  code: 'unauthorized',
  status: 401,
  headers: Headers {
    [Symbol(map)]: [Object: null prototype] {
      date: [ 'Fri, 17 May 2024 12:56:05 GMT' ],
      'content-type': [ 'application/json; charset=utf-8' ],
      'content-length': [ '139' ],
      connection: [ 'close' ],
      'x-powered-by': [ 'Express' ],
      'x-notion-request-id': [ '292c30e5-d974-4616-9f41-43fa3fd9879b' ],
      etag: [ 'W/"8b-UWHwSzH5gwyCwmWxCuPQ0+ZNgYU"' ],
      vary: [ 'Accept-Encoding' ],
      'cf-cache-status': [ 'DYNAMIC' ],
      'set-cookie': [
        '__cf_bm=wXO5ej6IxcYUNXKeUWkC2qPlG_hGpRaWu0czsxm4H.4-17[15](https://github.com/ilikui/home/actions/runs/9128577635/job/25101208584#step:4:16)950565-1.0.1.1-ADt6waGQ.GTaqVo690fBWBxaDCjxmpbpmlYzC92nGzglM3RcyhFFeauLfF3cPIYakeFmIVubud1stcQK4fPYqQ; path=/; expires=Fri, 17-May-24 13:26:05 GMT; domain=.notion.com; HttpOnly; Secure; SameSite=None'
      ],
      server: [ 'cloudflare' ],
      'cf-ray': [ '8853c3fa3d7682ae-IAD' ]
    }
  },
  body: '{"object":"error","status":401,"code":"unauthorized","message":"API token is invalid.","request_id":"292c30e5-d974-46[16](https://github.com/ilikui/home/actions/runs/9128577635/job/25101208584#step:4:17)-9f41-43fa3fd9879b"}'`

但是使用python是可以解析数据的

`
{'object': 'list', 'results': [{'object': 'page', 'id': '7304517b-d8e8-468f-9bd4-84cf9cd6748b', 'created_time': '2024-05-17T11:13:00.000Z', 'last_edited_time': '2024-05-17T11:13:00.000Z', 'created_by': {'object': 'user', 'id': 'e98cbe44-903e-46d0-a66b-e1da479f3616'}, 'last_edited_by': {'object': 'user', 'id': 'e98cbe44-903e-46d0-a66b-e1da479f3616'}, 'cover': None, 'icon': None, 'parent': {'type': 'database_id', 'database_id': 'f808fc9c-8cfb-4f2b-8350-25de9e55ec35'}, 'archived': False, 'in_trash': False, 'properties': {'rating': {'id': 'FjjM
`

**Comment by lizheming** [comment]
看起来就是说 Token 有问题，这是 Notion 那边的返回。你再确认下这几步都有没有做吧 https://github.com/lizheming/doumark-action?tab=readme-ov-file#sync-to-notion

**Comment by ilikui** [comment]
> 看起来就是说 Token 有问题，这是 Notion 那边的返回。你再确认下这几步都有没有做吧 https://github.com/lizheming/doumark-action?tab=readme-ov-file#sync-to-notion

谢谢，目前可以了，环境变量没有设置好
![image](https://github.com/lizheming/doumark-action/assets/11962397/fd1c47a8-fbf3-4ea1-b8c9-541cb3e79bba)
