### ISSUE TITLE
个人化评论评分数据？

### ISSUE THREAD

**Issue by conge** [lizheming/doumark-action#3]
我尝试了一下这个action，good work！

我有个问题：目前，似乎存下来的数据，都是书籍的基本数据和大众评分星级数据

不知道能不能把个人的评分，标签和简评数据也拿下来？

谢谢

**Comment by lizheming** [comment]
个人评分是有的，倒数第二列 `star` 那一列你看下。标签简评我看下有没有之后补充一下。

**Comment by conge** [comment]
> 个人评分是有的，倒数第二列 `star` 那一列你看下。标签简评我看下有没有之后补充一下。

那个star也是公众评出的。

比如这本书 https://book.douban.com/subject/35860667/ 
我给了它4星评价
但doumark-action 抓下来的数据，star 和 rating 都是0。

我意识到，要想抓个人给出的评价，标签，和星标，估计得提供登陆信息才行……
会把这个action变得更加复杂……

**Comment by lizheming** [comment]
不用的，个人的评价是公开的，不需要登录可以看到，除非是一些书影音被限制了需要登录才能查看信息的那种需要登录信息，其它的不需要。比如你的已读书时可以在这里看到的 https://book.douban.com/people/conge/collect 非登录就可以看到。
star 为 0 之后一并看下吧，理论上不会有问题。

**Comment by conge** [comment]
原来是这样。涨知识了。谢谢。
期待新版本。

**Comment by lizheming** [comment]
增加了 `tags` 和 `comment` 的数据返回，可以再试试。另外如果需要更多数据的话可以选择 `json` 存储方式，会把原始数据都存储下来。
关于 star 为 0 我试了下并没有复现这个问题，我看是正确抓取到 4 星的。如果没有的话唯一的可能就是这个 4 星是后期改的，抓取的时候可能还是 0 星。

**Comment by conge** [comment]
确认一下。你这里改了的话，用户端是不是不用任何改动，就能用到新版了，对吗？

**Comment by lizheming** [comment]
应该是的
