### ISSUE TITLE
想看/正在看

### ISSUE THREAD

**Issue by ihavenoideaa** [lizheming/doumark-action#7]
如何才能获取想看的电影 /书，或者正在看的电影/书

**Comment by lizheming** [comment]
https://github.com/lizheming/drone-doumark/blob/master/src/douban.js#L12 接口里有参数，目前没有开放出来，我支持下参数配置吧

**Comment by lizheming** [comment]
加上啦，status=mark 想看，status=doing 正在看，试试吧。

**Comment by ihavenoideaa** [comment]
谢谢大佬，很好用。
不过还有个小问题，就是csv文件更新只是能往里面加信息，删除还是要手动删除。
能不能：识别到更新后，直接创建一个新文件然后覆盖掉原文件，而不是只是添加数据

**Comment by lizheming** [comment]
接口并没有感知「变化」这个事情，只是单纯的按照时间抓取了所有的数据，通过时间游标来感知「增量」。如果要感知「变化」，那在每次数据同步的时候需要线上全量和本地全量数据做对比，这个对豆瓣的服务器压力太大了，被豆瓣感知到的话很可能会封禁 API，得不偿失。

建议你自己写个脚本处理一下，应该不复杂。

**Comment by ihavenoideaa** [comment]
了解！

**Comment by ihavenoideaa** [comment]
顺便提醒以下，readme那里status写错了，写成stauts了
