### ISSUE TITLE
关于豆瓣图片无法直接使用的说明

### ISSUE THREAD

**Issue by lizheming** [lizheming/doumark-action#8]
最近豆瓣对 CDN 的防盗链做了策略升级，外站无法直接使用豆瓣图片地址加载了。  
为了解决这个问题，我这里制作了个豆瓣海报的托管服务，图片地址规则如下：

```
https://dou.img.lithub.cc/<movie|book|music>/<id>.jpg
```

例如：https://dou.img.lithub.cc/movie/35769236.jpg

**Comment by TheWanderingAllison** [comment]
你好，请问为什么我把图片路径改成上面的格式还是没办法显示呀，
比如像这个地址，https://dou.img.lithub.cc/book/3634243568.jpg
错误是Internal Server Error，是还需要设置什么吗

**Comment by TheWanderingAllison** [comment]
> 你好，请问为什么我把图片路径改成上面的格式还是没办法显示呀， 比如像这个地址，https://dou.img.lithub.cc/book/3634243568.jpg 错误是Internal Server Error，是还需要设置什么吗

啊不好意思我发现问题了，原来id 并不是csv表格里的id，而是豆瓣url 的最后那串数字……

**Comment by lizheming** [comment]
@TheWanderingAllison 嗯，那个应该是个 Bug...我也是这次才反应过来那个 id 有问题……

**Comment by lizheming** [comment]
更新：最新的版本里已经修复了输出的 id 不是豆瓣 id 的问题，同时默认输出的封面图地址已经替换成了 `https://dou.img.lithub.cc` 镜像服务。

**Comment by newness33** [comment]
我在同步时也会有评分游戏的习惯，如果可以，请把game也添加一下

**Comment by lizheming** [comment]
@newness33 game 只是没有说明，你直接指定 `DOUBAN_TYPE=game` 是可以正常同步到的

**Comment by newness33** [comment]
> 

@lizheming  例如我玩过的一个游戏【荒野大镖客：救赎2 Red Dead Redemption 2】https://www.douban.com/game/26815212/ ，访问https://dou.img.lithub.cc/game/26815212.jpg 并没有同步到

**Comment by lizheming** [comment]
> @lizheming 例如我玩过的一个游戏【荒野大镖客：救赎2 Red Dead Redemption 2】https://www.douban.com/game/26815212/ ，访问https://dou.img.lithub.cc/game/26815212.jpg 并没有同步到

这个可以了，我之前以为你说的是 doumark-action 要同步游戏的记录

**Comment by ghost** [comment]
图床挂了？你的 https://imnerd.org/douban.html 无法显示图片了
比如 https://book.douban.com/subject/35902211/ 对应的 "cover_url": "https://dou.img.lithub.cc/book/35902211.jpg",也无法显示图片

**Comment by lizheming** [comment]
@isooosi 看了下，是我的服务使用超额被停了，目前先换了个账号重新部署服务临时解决下，后面再看看有没有什么其他的方案。有需要可以你自己部署自己的服务规避大家集中使用带来的超额问题 https://deta.space/discovery/@lizheming/dover

**Comment by ghost** [comment]
> @isooosi 看了下，是我的服务使用超额被停了，目前先换了个账号重新部署服务临时解决下，后面再看看有没有什么其他的方案。有需要可以你自己部署自己的服务规避大家集中使用带来的超额问题 https://deta.space/discovery/@lizheming/dover

deta 真是个宝藏应用

**Comment by ghost** [comment]
@lizheming 使用 https://deta.space/discovery/@lizheming/dover 某些封面获取失败，有的在你的 lithub.cc 可以获取成功，但在我的个人账户下无法获取。相反的情况也有。试了好多次了，还没成功。

**Comment by ghost** [comment]
终于成功了，应该是 douban 限速导致获取超时。

**Comment by TheWanderingAllison** [comment]
你好，最近这个豆瓣图片托管服务似乎又失效了，我用了上面的deta服务部署成功，但是有个问题是用doumark-action 生成的csv 文件里默认的原来的 `https://dou.img.lithub.cc/<movie|book|music>/<id>.jpg` ，请问有什么办法能让GitHub action 同步豆瓣数据时就把图片地址改成自己的呢

**Comment by TheWanderingAllison** [comment]
> 更新：最新的版本里已经修复了输出的 id 不是豆瓣 id 的问题，同时默认输出的封面图地址已经替换成了 `https://dou.img.lithub.cc` 镜像服务。

你好，这个镜像服务最近又失效了，我用了上面的 https://deta.space/discovery/@lizheming/dover 部署了自己的服务，但现在有个问题是，用doumark-action同步豆瓣生成的csv文件里poster默认的还是`https://dou.img.lithub.cc`，请问有办法在同步时就改成自己的deta服务对应的图片地址吗。

**Comment by lizheming** [comment]
@TheWanderingAllison id 在数据里有返回，type 你可以知道，你可以不用返回的数据的值，自己拼那个 poster 的值就行~ dou.img.lithub.cc 我之后再修一下~

**Comment by BachWV** [comment]
dou.im

> @TheWanderingAllison id 在数据里有返回，type 你可以知道，你可以不用返回的数据的值，自己拼那个 poster 的值就行~ dou.img.lithub.cc 我之后再修一下~

加油，就等着了

**Comment by TheWanderingAllison** [comment]
> 看了下，是我的服务使用超额被停了，目前先换了个账号重新部署服务临时解决下，后面再看看有没有什么其他的方案。有需要可以你自己部署自己的服务规避大家集中使用带来的超额问题 https://deta.space/discovery/@lizheming/dover

你好，前阵子收到deta的邮件说它们要关闭了，我之前是用你提供的这个 deta 应用部署了自己的服务，不知道关停之后还有没有其他的方案来使用豆瓣图片呢。
